checkpoint_dir: checkpoints
results_dir: results

batchsize: 4

models:
  unet:
    name: UNet
    input_channels: 3
    filters: [16, 64, 128, 128, 256, 256]
    layer_normalisation: False
    optimizer: "adam"
    lr: 0.0001
    loss: "mse"
    loss_weight: 1

  ClassicalDiscriminator:
    name: ClassicalDiscriminator
    filters: [64, 128, 256, 512, 512, 1]
    optimizer: "adam"
    lr: 0.0001
    loss: "binary_crossentropy"
    loss_weight: 0.001

  UnetXUnetT:
    name: UnetXUnetT
    filters: [16, 64, 128, 128, 256, 256]
    optimizer: "adam"
    lr: 0.0001
    loss: "mse"
    loss_weight: 25

dataset:
  dataset_name: IndigoMobile
  args:
    symbol_size: 6
    templates_path: ../data/binary/
    printed_path: ../data/original/crop/
    bad_indices: []
    template_target_size: [320, 320]
    target_size: [320, 320, 3]
    synchronize_with_template: False
    augmentation: True
    augmentation_args:
      first_order: ["rotation"]
      second_order: ["gamma"]
      rotation_angles: [0, 90, 180, 270]
      gamma: [0.5, 1.2, 0.1] # [start, end, step]
      flip: [0, 1] # ["horizontal", "vertical"]
    train_ratio: 0.4 # 60% (2 samples for training)
    val_ratio: 0.1 # 20% (1 sample for validation)
    test_ration: 0.5 # 20% (1 sample for test)




